sudo: required
language: generic
dist: xenial
services:
  - docker

env:
  matrix:
    - ROS_DISTRO="kinetic"

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci

script:
  - cd industrial_ci/industrial_ci/src/tests
  - chmod 777 source_tests.sh
  - ./source_tests.sh
